[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SagittalAverage"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = [
  "src/sagittal_average",
]