[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Sagittal_Brain_Averages"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = [
  "src/sagittal_brain",
]

[tool.pytest.ini_options] 
pythonpath = ["src"]